# Site
name: "omps.in"
title: "Om Blogs Here!!"
description: "I am Om.
 and this is my blogging journey."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
google_analytics: 'UA-7006734-1'
disqus: 'omps-in'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  omps:
    name: omps
    display_name: omps
    gravatar: 3f6e34f191fecf56d95f0297fbb5b705
    email: contact@omps.in
    web: https://www.omps.in
    twitter: https://twitter.com/ohgnis
    description: "Author at omps, My blogging journey."
  # john:
  #   name: John
  #   display_name: John
  #   avatar: 'assets/images/avatar.png'
  #   gravatar: b1cc14991db7a456fcd761680bbc8f81
  #   email: wowthemesnet@gmail.com
  #   web: https://www.wowthemes.net
  #   twitter: https://twitter.com/wowthemesnet
  #   description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

#Social
twitter_username:     ohgnis
github_username:      omps
linkedin_username:    ompsingh
google_plus_username: +OmPrakashomps
facebook_username:    ompnix
dribbble_username:
instagram_username: ompnix
exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
